services:
  xelsync-frontend:
    build:
      context: ./frontend-xelsync-ai
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api/v1
    container_name: xelsync-frontend-app
    networks:
      - xelsync_net
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api/v1

networks:
  xelsync_net:
    external: true
    name: xelsync_network
